// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityMonitorApi.Data;

#nullable disable

namespace SecurityMonitorApi.Migrations
{
    [DbContext(typeof(SecurityMonitorContext))]
    [Migration("20260304133110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityMonitorApi.Models.AttackStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlockedCount")
                        .HasColumnType("int")
                        .HasColumnName("blocked_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<string>("TopIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("top_ip");

                    b.Property<string>("TopUsername")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("top_username");

                    b.Property<int?>("TotalAttacks")
                        .HasColumnType("int")
                        .HasColumnName("total_attacks");

                    b.Property<int?>("UniqueAttackers")
                        .HasColumnType("int")
                        .HasColumnName("unique_attackers");

                    b.Property<string>("VmId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vm_id");

                    b.HasKey("Id");

                    b.HasIndex("StatDate")
                        .HasDatabaseName("idx_stats_date");

                    b.HasIndex("StatDate", "VmId")
                        .IsUnique()
                        .HasDatabaseName("IX_AttackStatistics_StatDate_VmId")
                        .HasFilter("[stat_date] IS NOT NULL AND [vm_id] IS NOT NULL");

                    b.HasIndex("VmId", "StatDate")
                        .HasDatabaseName("idx_stats_vm");

                    b.ToTable("AttackStatistics", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.BlockedIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BlockExpires")
                        .HasColumnType("datetime2")
                        .HasColumnName("block_expires");

                    b.Property<DateTime>("BlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("blocked_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("BlockedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("auto")
                        .HasColumnName("blocked_by");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("global")
                        .HasColumnName("scope");

                    b.Property<string>("TargetVmId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("target_vm_id");

                    b.Property<DateTime?>("UnblockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("unblocked_at");

                    b.Property<string>("UnblockedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unblocked_by");

                    b.HasKey("Id");

                    b.HasIndex("BlockExpires")
                        .HasDatabaseName("idx_blocked_expires");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_blocked_active");

                    b.HasIndex("Scope", "IsActive")
                        .HasDatabaseName("idx_blocked_scope");

                    b.ToTable("BlockedIPs", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.FailedLoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4625)
                        .HasColumnName("event_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("LogonType")
                        .HasColumnType("int")
                        .HasColumnName("logon_type");

                    b.Property<int?>("SourcePort")
                        .HasColumnType("int")
                        .HasColumnName("source_port");

                    b.Property<string>("SourceVmId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_vm_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_timestamp");

                    b.HasIndex("IpAddress", "Timestamp")
                        .HasDatabaseName("idx_ip_timestamp");

                    b.HasIndex("SourceVmId", "Timestamp")
                        .HasDatabaseName("idx_source_vm");

                    b.HasIndex("IpAddress", "Username", "SourcePort", "Timestamp", "SourceVmId")
                        .HasDatabaseName("idx_dedup_check");

                    b.ToTable("FailedLoginAttempts", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.PerVmThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoBlockEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_block_enabled");

                    b.Property<int>("BlockDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("block_duration_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Threshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("threshold");

                    b.Property<int>("TimeWindowMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasColumnName("time_window_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vm_id");

                    b.HasKey("Id");

                    b.HasIndex("VmId")
                        .IsUnique();

                    b.ToTable("PerVMThresholds", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.Setting", b =>
                {
                    b.Property<string>("KeyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("value");

                    b.HasKey("KeyName");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            KeyName = "THRESHOLD",
                            Description = "Failed attempts before marking as suspicious",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "5"
                        },
                        new
                        {
                            KeyName = "TIME_WINDOW",
                            Description = "Time window in minutes for threshold",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "5"
                        },
                        new
                        {
                            KeyName = "BLOCK_DURATION",
                            Description = "Auto-block duration in minutes",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "60"
                        },
                        new
                        {
                            KeyName = "ENABLE_AUTO_BLOCK",
                            Description = "Enable automatic IP blocking",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "true"
                        },
                        new
                        {
                            KeyName = "GLOBAL_THRESHOLD",
                            Description = "Global threshold across all VMs",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "5"
                        },
                        new
                        {
                            KeyName = "ENABLE_GLOBAL_AUTO_BLOCK",
                            Description = "Enable global auto-blocking",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "true"
                        });
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.SuspiciousIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("FirstAttempt")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_attempt");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LastAttempt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_attempt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TargetUsernames")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target_usernames");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique()
                        .HasDatabaseName("idx_suspicious_ip");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_suspicious_status");

                    b.ToTable("SuspiciousIPs", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.VmSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("collection_method");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("VmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vm_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_vmsources_status");

                    b.HasIndex("VmId")
                        .IsUnique()
                        .HasDatabaseName("idx_vmsources_vm_id");

                    b.ToTable("VMSources", (string)null);
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.PerVmThreshold", b =>
                {
                    b.HasOne("SecurityMonitorApi.Models.VmSource", "VmSource")
                        .WithOne("PerVmThreshold")
                        .HasForeignKey("SecurityMonitorApi.Models.PerVmThreshold", "VmId")
                        .HasPrincipalKey("SecurityMonitorApi.Models.VmSource", "VmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VmSource");
                });

            modelBuilder.Entity("SecurityMonitorApi.Models.VmSource", b =>
                {
                    b.Navigation("PerVmThreshold");
                });
#pragma warning restore 612, 618
        }
    }
}
